### チュートリアルの学習
- https://yutaroogawa.github.io/pytorch_tutorials_jp/

In [1]:
import torch

In [2]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [4]:
print(y.grad_fn)

In [5]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [6]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [7]:
out.backward()

In [8]:
print(out)

tensor(27., grad_fn=<MeanBackward0>)


In [9]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [10]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([1160.9286,  217.0449,   11.1450], grad_fn=<MulBackward0>)


In [16]:
# norm は ユークリッドきょり
test = torch.randn(2)
test = test * 2
test, test.data.norm()

(tensor([-4.1953, -2.8585]), tensor(5.0765))

In [17]:
# 答えが同じになるはず
torch.sqrt(y[0] * y[0] + y[1] * y[1] + y[2]*y[2])

tensor(1181.0961, grad_fn=<SqrtBackward0>)

In [18]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([4.0960e+02, 4.0960e+03, 4.0960e-01])


In [22]:
print(x.requires_grad)
print((x ** 2).requires_grad)

print(f"requries: {x.requires_grad}")


# no_grad() の間は勾配が更新されない
with torch.no_grad():
	print((x ** 2).requires_grad)

True
True
requries: True
False
